export const projects = [
  {
    id: "01",
    title: "Portfolio Website",
    description:
      "A personal portfolio built with Next.js and Tailwind CSS to showcase projects, skills, and experience with smooth animations and responsive design.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Portfolio",
    liveUrl: "https://muhammed-jasir-m.vercel.app/",
    skills: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Shadcn UI",
    ],
    category: "Frontend Website",
    image: "/assets/screenshots/portfolio.png",
    repoType: "private",
  },
  {
    id: "02",
    title: "Dekozy E-Commerce App",
    description:
      "A feature-rich e-commerce mobile app developed using Flutter with Firebase authentication, product management, and image handling via Cloudinary.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Dekozy",
    apkUrl: "",
    skills: ["Flutter", "Firebase", "Dart", "GetX", "Cloudinary"],
    category: "Fullstack Mobile App",
    image: "/assets/screenshots/dekozy.png",
    repoType: "private",
  },
  {
    id: "03",
    title: "Movie Flick",
    description:
      "A React-based movie discovery platform using TMDB API for content and Firebase for user authentication and data management.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Movie-Flick",
    liveUrl: "https://movie-flick.vercel.app/",
    skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API", "Firebase"],
    category: "Fullstack Website",
    image: "/assets/screenshots/movie_flick.png",
    repoType: "private",
  },
  {
    id: "04",
    title: "Netflix Clone",
    description:
      "A responsive Netflix-inspired web app built with React and Firebase, featuring movie browsing, trailers, and real-time database integration.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Netflix-Clone",
    liveUrl: "https://netflix-clone-nine-jade.vercel.app/",
    skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API", "Firebase"],
    category: "Fullstack Website",
    image: "/assets/screenshots/netflix_clone.png",
    repoType: "public",
  },
  {
    id: "05",
    title: "Dekozy Admin Panel",
    description:
      "A web-based admin dashboard for the Dekozy e-commerce platform, built using Flutter Web for managing products, orders, and analytics.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Dekozy-Admin-Panel",
    liveUrl: "https://aura-kart.web.app/dashboard",
    skills: ["Flutter", "Firebase", "Dart", "GetX", "Cloudinary"],
    category: "Fullstack Web App",
    image: "/assets/screenshots/dekozy_admin_panel.png",
    repoType: "private",
  },
  {
    id: "06",
    title: "The Blog Spot",
    description:
      "A full-featured MERN blog site allowing users to create, edit, and delete posts with rich UI components using Flowbite and Tailwind CSS.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Mern-Blog-Site",
    liveUrl: "https://mern-blog-site-x2re.onrender.com/",
    skills: [
      "MongoDB",
      "Express.js",
      "React",
      "Node.js",
      "Tailwind CSS",
      "Flowbite",
    ],
    category: "Fullstack Website",
    image: "/assets/screenshots/the_blog_spot.png",
    repoType: "public",
  },
  {
    id: "07",
    title: "Shopping Cart",
    description:
      "A simple Node.js and Express-based e-commerce site using Handlebars for templating and MongoDB for product and cart management.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Shopping-Cart",
    liveUrl: "https://shopping-cart-xcmk.onrender.com/",
    skills: ["MongoDB", "Express.js", "Handlebars", "Node.js", "Bootstrap"],
    category: "Fullstack Website",
    image: "/assets/screenshots/shopping_cart.png",
    repoType: "public",
  },
  {
    id: "08",
    title: "Tic Tac Toe",
    description:
      "A responsive Tic Tac Toe game built with React and TypeScript, featuring dynamic board state, win detection, and simple animations.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Tic-Tac-Toe",
    liveUrl: "https://tic-tac-toe-99acde.netlify.app/",
    skills: ["React", "TypeScript", "Tailwind CSS"],
    category: "Frontend Website",
    image: "/assets/screenshots/tic_tac_toe.png",
    repoType: "public",
  },
  {
    id: "09",
    title: "Calculator App",
    description:
      "A sleek calculator app built using Flutter that supports basic arithmetic operations with a clean and intuitive UI.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Calculator-App",
    apkUrl: "",
    skills: ["Flutter", "Dart"],
    category: "Frontend Mobile App",
    image: "/assets/screenshots/calculator_app.png",
    repoType: "public",
  },
  {
    id: "10",
    title: "Ar Model App",
    description:
      "An AR-powered Flutter mobile app for rendering and interacting with 3D models using device camera and AR libraries.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Ar-Flutter-App",
    apkUrl: "",
    skills: ["Flutter", "Dart"],
    category: "Frontend Mobile App",
    image: "/assets/screenshots/ar_model_app.png",
    repoType: "public",
  },
  {
    id: "11",
    title: "Calculator Web",
    description:
      "A browser-based calculator built with React and Tailwind CSS, offering a simple interface for basic math operations.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Web-Calculator",
    liveUrl: "https://muhammed-jasir-m.github.io/Web-Calculator/",
    skills: ["React", "JavaScript", "Tailwind CSS"],
    category: "Frontend Website",
    image: "/assets/screenshots/web_calculator.png",
    repoType: "public",
  },
  {
    id: "12",
    title: "Rock Paper Scissors",
    description:
      "A classic Rock-Paper-Scissors game built with HTML, CSS, and JavaScript featuring interactive UI and score tracking.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Rock-Paper-Scissors",
    liveUrl: "https://muhammed-jasir-m.github.io/Rock-Paper-Scissors/",
    skills: ["HTML", "CSS", "JavaScript"],
    category: "Frontend Website",
    image: "/assets/screenshots/rock_paper_scissors.png",
    repoType: "public",
  },
  {
    id: "13",
    title: "Nike Clone",
    description:
      "A visually appealing clone of the Nike website, built with React and Tailwind CSS to practice UI replication and responsiveness.",
    githubUrl: "https://github.com/Muhammed-Jasir-M/Nike-Clone",
    liveUrl: "https://nike-clone-197a27.netlify.app/",
    skills: ["React", "JavaScript", "Tailwind CSS"],
    category: "Frontend Website",
    image: "/assets/screenshots/nike_clone.png",
    repoType: "public",
  },
];
