export const projects = {
  title: "Projects",
  items: [
    {
      id: "01",
      title: "Portfolio Website",
      description:
        "Personal portfolio built with Next.js and Tailwind CSS. Features smooth animations, responsive layout, and elegant UI using Shadcn and Framer Motion.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Portfolio",
      liveUrl: "https://muhammed-jasir-m.vercel.app/",
      skills: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Framer Motion",
        "Shadcn UI",
      ],
      category: "Frontend",
      image: "/assets/screenshots/portfolio.png",
      repoType: "private",
    },
    {
      id: "02",
      title: "Dekozy E-Commerce App",
      description:
        "Full-featured Flutter e-commerce app with Firebase auth, real-time product updates, Cloudinary support, and state managed via GetX.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Dekozy",
      apkUrl: "",
      skills: ["Flutter", "Firebase", "Dart", "GetX", "Cloudinary"],
      category: "Mobile",
      image: "/assets/screenshots/dekozy.jpeg",
      repoType: "private",
    },
    {
      id: "03",
      title: "Movie Flick",
      description:
        "Movie platform using TMDB API and Firebase. Includes auth, trending carousels, watchlists, and a responsive, clean interface.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Movie-Flick",
      liveUrl: "https://movie-flick.vercel.app/",
      skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API", "Firebase"],
      category: "Fullstack",
      image: "/assets/screenshots/movie_flick.png",
      repoType: "private",
    },
    {
      id: "04",
      title: "Netflix Clone",
      description:
        "A Netflix-inspired site with Firebase auth, movie trailers, and category-based browsing. Built with React and Tailwind CSS.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Netflix-Clone",
      liveUrl: "https://netflix-clone-nine-jade.vercel.app/",
      skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API", "Firebase"],
      category: "Fullstack",
      image: "/assets/screenshots/netflix_clone.png",
      repoType: "public",
    },
    {
      id: "05",
      title: "Dekozy Admin Panel",
      description:
        "Flutter Web admin dashboard for managing products, orders, and analytics. Integrates Firebase, Cloudinary, and responsive design.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Dekozy-Admin-Panel",
      liveUrl: "https://aura-kart.web.app/dashboard",
      skills: ["Flutter", "Firebase", "Dart", "GetX", "Cloudinary"],
      category: "Fullstack",
      image: "/assets/screenshots/dekozy_admin_panel.png",
      repoType: "private",
    },
    {
      id: "06",
      title: "The Blog Spot",
      description:
        "A full-featured blog platform with rich text editing, user auth, and Flowbite UI components. Built with the MERN stack.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Mern-Blog-Site",
      liveUrl: "https://mern-blog-site-x2re.onrender.com/",
      skills: [
        "MongoDB",
        "Express.js",
        "React",
        "Node.js",
        "Tailwind CSS",
        "Flowbite",
      ],
      category: "Fullstack",
      image: "/assets/screenshots/the_blog_spot.png",
      repoType: "public",
    },
    {
      id: "07",
      title: "Shopping Cart",
      description:
        "Node.js app with MongoDB and Handlebars for product CRUD and cart session handling. Features a full shopping flow.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Shopping-Cart",
      liveUrl: "https://shopping-cart-xcmk.onrender.com/",
      skills: ["MongoDB", "Express.js", "Handlebars", "Node.js", "Bootstrap"],
      category: "Fullstack",
      image: "/assets/screenshots/shopping_cart.png",
      repoType: "public",
    },
    {
      id: "08",
      title: "Tic Tac Toe",
      description:
        "A clean, responsive Tic Tac Toe game with TypeScript and React. Includes subtle animations and a mobile-friendly UI.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Tic-Tac-Toe",
      liveUrl: "https://tic-tac-toe-99acde.netlify.app/",
      skills: ["React", "TypeScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/tic_tac_toe.png",
      repoType: "public",
    },
    {
      id: "09",
      title: "Calculator App",
      description:
        "A Flutter-based calculator with a sleek UI and built-in BMI calculator. Smooth performance and cross-platform ready.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Calculator-App",
      apkUrl: "",
      skills: ["Flutter", "Dart"],
      category: "Mobile",
      image: "/assets/screenshots/calculator_app.jpeg",
      repoType: "public",
    },
    {
      id: "10",
      title: "Ar Model App",
      description:
        "AR-based Flutter app for 3D model interaction and viewing. Includes model info, AR mode, and clean user experience.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Ar-Flutter-App",
      apkUrl: "",
      skills: ["Flutter", "Dart"],
      category: "Mobile",
      image: "/assets/screenshots/ar_model_app.jpeg",
      repoType: "public",
    },
    {
      id: "11",
      title: "Calculator Web",
      description:
        "A browser-based calculator built with React and Tailwind CSS. Simple UI for quick, responsive math operations.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Web-Calculator",
      liveUrl: "https://muhammed-jasir-m.github.io/Web-Calculator/",
      skills: ["React", "JavaScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/web_calculator.png",
      repoType: "public",
    },
    {
      id: "12",
      title: "Rock Paper Scissors",
      description:
        "Classic Rock-Paper-Scissors game with an interactive interface and score tracking. Built using vanilla JavaScript.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Rock-Paper-Scissors",
      liveUrl: "https://muhammed-jasir-m.github.io/Rock-Paper-Scissors/",
      skills: ["HTML", "CSS", "JavaScript"],
      category: "Frontend",
      image: "/assets/screenshots/rock_paper_scissors.png",
      repoType: "public",
    },
    {
      id: "13",
      title: "Nike Clone",
      description:
        "A pixel-perfect Nike landing page clone made using React and Tailwind CSS. Focuses on UI replication and responsiveness.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Nike-Clone",
      liveUrl: "https://nike-clone-197a27.netlify.app/",
      skills: ["React", "JavaScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/nike_clone.png",
      repoType: "public",
    },
  ],
};
