export const projects = {
  title: "Projects",
  items: [
    {
      id: "01",
      title: "Portfolio Website",
      description:
        "Modern portfolio built with Next.js and Tailwind CSS featuring animated transitions, responsive layouts, and elegant UI components from Shadcn. Includes Framer Motion for smooth animations and showcases professional work effectively.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Portfolio",
      liveUrl: "https://muhammed-jasir-m.vercel.app/",
      skills: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Framer Motion",
        "Shadcn UI",
      ],
      category: "Frontend",
      image: "/assets/screenshots/portfolio.png",
      repoType: "private",
    },
    {
      id: "02",
      title: "Movie Flick",
      description:
        "Comprehensive movie platform integrating TMDB API with Firebase backend. Features user authentication, trending carousels, personalized watchlists, and responsive Tailwind CSS styling.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Movie-Flick",
      liveUrl: "https://movie-flick.vercel.app/",
      skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API", "Firebase"],
      category: "Fullstack",
      image: "/assets/screenshots/movie_flick.png",
      repoType: "private",
    },
    {
      id: "03",
      title: "Netflix Clone",
      description:
        "Responsive Netflix-inspired platform with Firebase authentication and TMDB API integration. Features movie trailers, category browsing, and Tailwind CSS styling for modern UI components.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Netflix-Clone",
      liveUrl: "https://netflix-clone-nine-jade.vercel.app/",
      skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API", "Firebase"],
      category: "Fullstack",
      image: "/assets/screenshots/netflix_clone.png",
      repoType: "public",
    },
    {
      id: "04",
      title: "The Blog Spot",
      description:
        "Full-stack blog platform built with MERN stack featuring rich text editing, user authentication, and Flowbite UI components. MongoDB backend with Express.js and React frontend.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Mern-Blog-Site",
      liveUrl: "https://mern-blog-site-x2re.onrender.com/",
      skills: [
        "MongoDB",
        "Express.js",
        "React",
        "Node.js",
        "Tailwind CSS",
        "Flowbite",
      ],
      category: "Fullstack",
      image: "/assets/screenshots/the_blog_spot.png",
      repoType: "public",
    },
    {
      id: "05",
      title: "Shopping Cart",
      description:
        "Node.js e-commerce application with MongoDB database and Handlebars templating. Implements product management, cart functionality, and Bootstrap UI components.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Shopping-Cart",
      liveUrl: "https://shopping-cart-xcmk.onrender.com/",
      skills: ["MongoDB", "Express.js", "Handlebars", "Node.js", "Bootstrap"],
      category: "Fullstack",
      image: "/assets/screenshots/shopping_cart.png",
      repoType: "public",
    },
    {
      id: "06",
      title: "Tic Tac Toe",
      description:
        "Interactive Tic Tac Toe game built with React and TypeScript. Features responsive design with Tailwind CSS, game state management, and subtle animations.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Tic-Tac-Toe",
      liveUrl: "https://tic-tac-toe-99acde.netlify.app/",
      skills: ["React", "TypeScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/tic_tac_toe.png",
      repoType: "public",
    },
    {
      id: "07",
      title: "Calculator App",
      description:
        "Flutter-based calculator application with clean UI design. Includes standard calculator functions along with BMI calculation feature and smooth performance.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Calculator-App",
      apkUrl: "",
      skills: ["Flutter", "Dart"],
      category: "Mobile",
      image: "/assets/screenshots/calculator_app.jpeg",
      repoType: "public",
    },
    {
      id: "08",
      title: "Ar Model App",
      description:
        "Augmented Reality application built with Flutter for 3D model visualization. Features model interaction, information display, and AR viewing capabilities.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Ar-Flutter-App",
      apkUrl: "",
      skills: ["Flutter", "Dart"],
      category: "Mobile",
      image: "/assets/screenshots/ar_model_app.jpeg",
      repoType: "public",
    },
    {
      id: "09",
      title: "Calculator Web",
      description:
        "Web-based calculator application developed with React and Tailwind CSS. Provides responsive design and performs basic arithmetic operations efficiently.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Web-Calculator",
      liveUrl: "https://muhammed-jasir-m.github.io/Web-Calculator/",
      skills: ["React", "JavaScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/web_calculator.png",
      repoType: "public",
    },
    {
      id: "10",
      title: "Rock Paper Scissors",
      description:
        "Classic game implementation using vanilla JavaScript. Features interactive UI with score tracking, responsive design, and simple game mechanics.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Rock-Paper-Scissors",
      liveUrl: "https://muhammed-jasir-m.github.io/Rock-Paper-Scissors/",
      skills: ["HTML", "CSS", "JavaScript"],
      category: "Frontend",
      image: "/assets/screenshots/rock_paper_scissors.png",
      repoType: "public",
    },
    {
      id: "11",
      title: "Nike Clone",
      description:
        "Responsive Nike landing page clone built with React and Tailwind CSS. Replicates original design elements with attention to detail and mobile responsiveness.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Nike-Clone",
      liveUrl: "https://nike-clone-197a27.netlify.app/",
      skills: ["React", "JavaScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/nike_clone.png",
      repoType: "public",
    },
    {
      id: "12",
      title: "Money Tracker App",
      description:
        "Flutter expense tracking application with Bloc state management and Hive database. Features intuitive UI for recording expenses, categorizing transactions, and visualizing spending patterns with charts.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Money-Tracker-App",
      apkUrl: "",
      skills: ["Flutter", "Dart", "Bloc", "Hive"],
      category: "Mobile",
      image: "/assets/screenshots/money_tracker.png",
      repoType: "public",
    },
    {
      id: "13",
      title: "Olx Clone",
      description:
        "Classified ads platform clone with React and Firebase backend. Implements user authentication, ad posting functionality, and search features with responsive Tailwind CSS styling.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Olx-Clone",
      liveUrl: "https://olx-clone-chi-green.vercel.app/",
      skills: ["React", "JavaScript", "Firebase", "Tailwind CSS"],
      category: "Fullstack",
      image: "/assets/screenshots/olx_clone.png",
      repoType: "public",
    },
    {
      id: "14",
      title: "Disney Clone",
      description:
        "Streaming service clone featuring TMDB API integration for content display. Includes responsive carousels, movie details pages, and Tailwind CSS styling for Disney+ inspired interface.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Disney-Clone",
      liveUrl: "https://disney-clone-12df46.netlify.app/",
      skills: ["React", "JavaScript", "Tailwind CSS", "TMDB API"],
      category: "Frontend",
      image: "/assets/screenshots/disney.png",
      repoType: "public",
    },
    {
      id: "15",
      title: "Trip Planning Bot",
      description:
        "AI-powered travel assistant built with Python and Streamlit. Provides personalized itinerary suggestions, destination recommendations, and travel tips based on user preferences.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Trip-Planning-Bot",
      liveUrl: "https://trip-planning-bot-chatbot-xl82lz.streamlit.app/",
      skills: ["Python", "Streamlit"],
      category: "Frontend",
      image: "/assets/screenshots/trip_bot.png",
      repoType: "public",
    },
  ],
};

export const contributedProjects = {
  title: "Contributions",
  items: [
    {
      id: "01",
      title: "Dekozy E-Commerce App",
      description:
        "Feature-rich Flutter shopping app with Firebase authentication, real-time product updates, and Cloudinary media management. Uses GetX for efficient state management and offers seamless user experience.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Dekozy",
      apkUrl: "",
      skills: ["Flutter", "Firebase", "Dart", "GetX", "Cloudinary"],
      category: "Mobile",
      image: "/assets/screenshots/dekozy.jpeg",
      repoType: "private",
    },
    {
      id: "02",
      title: "Dekozy Admin Panel",
      description:
        "Flutter-based admin dashboard for e-commerce management with Firebase integration. Handles products, orders, analytics, and features Cloudinary media support with responsive design.",
      githubUrl: "https://github.com/Muhammed-Jasir-M/Dekozy-Admin-Panel",
      liveUrl: "https://aura-kart.web.app/dashboard",
      skills: ["Flutter", "Firebase", "Dart", "GetX", "Cloudinary"],
      category: "Fullstack",
      image: "/assets/screenshots/dekozy_admin_panel.png",
      repoType: "private",
    },
    {
      id: "03",
      title: "Notepad",
      description:
        "Cross-platform note-taking application built with Svelte and Tauri. Features markdown support, dark/light themes, and desktop app packaging with clean Shadcn UI components.",
      githubUrl: "https://github.com/Muhammed-Rahif/Notpad",
      liveUrl: "https://notpad-enhanced.vercel.app/",
      skills: ["Svelte", "Tauri", "Tailwind CSS", "Shadcn UI"],
      category: "Frontend",
      image: "/assets/screenshots/notepad.png",
      repoType: "public",
    },
    {
      id: "04",
      title: "E Commerce Site",
      description:
        "React-based online store prototype with product listings and shopping cart functionality. Features responsive Tailwind CSS design and interactive product browsing experience.",
      githubUrl: "https://github.com/sinankambran/ecommerce-app",
      liveUrl: "https://ecommerce-app-bay-eight.vercel.app/",
      skills: ["React", "JavaScript", "Tailwind CSS"],
      category: "Frontend",
      image: "/assets/screenshots/ecommerce.png",
      repoType: "public",
    },
    {
      id: "05",
      title: "Dedo Todo App",
      description:
        "Flutter task management application with Bloc architecture and SQLite local storage. Offers task categorization, priority levels, and offline capability with clean material design.",
      githubUrl: "https://github.com/Nihal-Mohammed-V/Dedov2",
      apkUrl: "",
      skills: ["Flutter", "Dart", "Sqlite", "Bloc"],
      category: "Mobile",
      image: "/assets/screenshots/dedo.png",
      repoType: "private",
    },
  ],
};
